plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - INDEX.md
  - LICENSE.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-hacker
