name: macOS
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    name: macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          brew install cmake
      - name: Configure & build
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DLIBRESSL_TESTS=OFF -DLIBRESSL_APPS=OFF ..
            cmake --build .
      - name: Run test examples
        run: |
            cd build
            ./go_channel
            ./go_select
            ./go_panic
            ./co_cpp_future_wait
            ./co_uv_fs
            ./co_uv_spawn
            ./co_uv_stream
